import ProjectDescription

public extension SettingValue {
  static let marketingVersion: SettingValue = "1.0"
  static let projectVersion: SettingValue = "1"
}

let scripts = [
  TargetScript.pre(
    script: "\"$PODS_ROOT/R.swift/rswift\" generate \"$SRCROOT/$PROJECT_NAME/Resource/AutoGenerated/R.generated.swift\"",
    name: "R.swift",
    inputPaths: [Path("$TEMP_DIR/rswift-lastrun")],
    outputPaths: [Path("$SRCROOT/$PROJECT_NAME/Resource/AutoGenerated/R.generated.swift")]
  ),
  TargetScript.post(
    script: "\"${PODS_ROOT}/SwiftLint/swiftlint\"",
    name: "Swift Lint"
  ),
  TargetScript.post(
    script: "$SRCROOT/$PROJECT_NAME/Script/GoogleService-Info.sh",
    name: "GoogleService-Info"
  ),
  TargetScript.post(
    script: "\"${PODS_ROOT}/FirebaseCrashlytics/run\"",
    name: "Firebase Crashlytics",
    inputPaths: [
      Path("\"${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}\""),
      Path("\"$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)\"")
    ]
  )
]

let baseSettings: [String: SettingValue] = [
  "ENABLE_BITCODE": "NO",
  "CURRENT_PROJECT_VERSION": .projectVersion,
  "MARKETING_VERSION": .marketingVersion,
  "DEVELOPMENT_TEAM": "45R995393Y"
]

let settings = Settings.settings(
  base: baseSettings,
  defaultSettings: .recommended
)

let ozet = Target(
  name: "OZET",
  platform: .iOS,
  product: .app,
  bundleId: "app.ozet.ios",
  deploymentTarget: .iOS(
    targetVersion: "13.0",
    devices: [.iphone]
  ),
  infoPlist: "OZET/Plist/Info.plist",
  sources: [
    "OZET/**"
  ],
  resources: ["OZET/Resource/**"],
  scripts: scripts,
  settings: settings
)

let project = Project(
  name: "OZET",
  organizationName: "app.OZET",
  targets: [
    ozet
  ],
  additionalFiles: [
    "OZET/GoogleService-Info.plist"
  ]
)
